### ISSUE TITLE
Migrate data import from global.r to server.r

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Stats-next-gen#131]
### Feature Description

When sormas db is empty, the app breaks because there is no data to analyse
### Problem Description

Allow app to launch even there is no data in sormas db
### Proposed Change

- migrate load data to server.r
- update all UI elements that depends on imported data with a default data
-  refs: https://rdrr.io/cran/shinyWidgets/man/updatePickerInput.html

**Comment by jwijffels** [comment]
@bernardsilenou 
I've created a merge request to fix this at https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen/pull/135

**Comment by jwijffels** [comment]
+ pull request https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen/pull/136 which loads the app without having access to the DB

**Comment by jwijffels** [comment]
The 2 pull requests moved the data loading to the server side except the fixed shapefiles 
Everything which fails due to either data connectivity or missing data in the database is now shown as an error message at the startup of the app. 

https://github.com/hzi-braunschweig/SORMAS-Stats-next-gen/blob/development/sormas-stats-shinyapp/sormas-stats-app/server.R#L6:L127
